
package org.ilu.pv.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b05
 * Generated source version: 2.2
 */
@WebService(name = "ProcessValueService", targetNamespace = "http://ws.pv.ilu.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProcessValueService {


  /**
   * @param arg0
   * @return returns org.ilu.pv.client.ProcessValueQueryFeedback
   * @throws ProcessValueQueryException_Exception
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "query", targetNamespace = "http://ws.pv.ilu.org/", className = "org.ilu.pv.client.Query")
  @ResponseWrapper(localName = "queryResponse", targetNamespace = "http://ws.pv.ilu.org/", className = "org.ilu.pv.client.QueryResponse")
  @Action(input = "http://ws.pv.ilu.org/ProcessValueService/queryRequest", output = "http://ws.pv.ilu.org/ProcessValueService/queryResponse", fault = {
      @FaultAction(className = ProcessValueQueryException_Exception.class, value = "http://ws.pv.ilu.org/ProcessValueService/query/Fault/ProcessValueQueryException")
  })
  public ProcessValueQueryFeedback query(
      @WebParam(name = "arg0", targetNamespace = "")
          ProcessValueQuery arg0)
      throws ProcessValueQueryException_Exception
  ;

}
