
package org.ilu.pv.client;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b05
 * Generated source version: 2.2
 */
@WebServiceClient(name = "ProcessValueServiceImplService", targetNamespace = "http://impl.ws.pv.ilu.org/", wsdlLocation = "http://localhost:9998/ProcessValueService?WSDL")
public class ProcessValueServiceImplService
    extends Service {

    private final static URL PROCESSVALUESERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException PROCESSVALUESERVICEIMPLSERVICE_EXCEPTION;
    private final static QName PROCESSVALUESERVICEIMPLSERVICE_QNAME = new QName("http://impl.ws.pv.ilu.org/", "ProcessValueServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9998/ProcessValueService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROCESSVALUESERVICEIMPLSERVICE_WSDL_LOCATION = url;
        PROCESSVALUESERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public ProcessValueServiceImplService() {
        super(__getWsdlLocation(), PROCESSVALUESERVICEIMPLSERVICE_QNAME);
    }

    public ProcessValueServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROCESSVALUESERVICEIMPLSERVICE_QNAME, features);
    }

    public ProcessValueServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, PROCESSVALUESERVICEIMPLSERVICE_QNAME);
    }

    public ProcessValueServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROCESSVALUESERVICEIMPLSERVICE_QNAME, features);
    }

    public ProcessValueServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProcessValueServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns ProcessValueService
     */
    @WebEndpoint(name = "ProcessValueServiceImplPort")
    public ProcessValueService getProcessValueServiceImplPort() {
        return super.getPort(new QName("http://impl.ws.pv.ilu.org/", "ProcessValueServiceImplPort"), ProcessValueService.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns ProcessValueService
     */
    @WebEndpoint(name = "ProcessValueServiceImplPort")
    public ProcessValueService getProcessValueServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.ws.pv.ilu.org/", "ProcessValueServiceImplPort"), ProcessValueService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROCESSVALUESERVICEIMPLSERVICE_EXCEPTION != null) {
            throw PROCESSVALUESERVICEIMPLSERVICE_EXCEPTION;
        }
        return PROCESSVALUESERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
