
package org.ilu.pv.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b05
 * Generated source version: 2.2
 */
@WebFault(name = "ProcessValueQueryException", targetNamespace = "http://ws.pv.ilu.org/")
public class ProcessValueQueryException_Exception
    extends Exception {

  /**
   * Java type that goes as soapenv:Fault detail element.
   */
  private ProcessValueQueryException faultInfo;

  /**
   * @param message
   * @param faultInfo
   */
  public ProcessValueQueryException_Exception(String message, ProcessValueQueryException faultInfo) {
    super(message);
    this.faultInfo = faultInfo;
  }

  /**
   * @param message
   * @param faultInfo
   * @param cause
   */
  public ProcessValueQueryException_Exception(String message, ProcessValueQueryException faultInfo, Throwable cause) {
    super(message, cause);
    this.faultInfo = faultInfo;
  }

  /**
   * @return returns fault bean: org.ilu.pv.client.ProcessValueQueryException
   */
  public ProcessValueQueryException getFaultInfo() {
    return faultInfo;
  }

}
