[main]
# Create and setup user filter.
user = com.remo.filters.FacesAjaxAwareUserFilter
user.loginUrl = /login.xhtml

# Create JDBC realm.
jdbcRealm = org.apache.shiro.realm.jdbc.JdbcRealm

dataSource = org.postgresql.ds.PGSimpleDataSource
dataSource.user = postgres
dataSource.password = postgres
dataSource.databaseName = remo
dataSource.serverName = localhost
dataSource.portNumber = 5432

jdbcRealm.dataSource = $dataSource

# Configure JDBC realm SQL queries.
jdbcRealm.authenticationQuery = SELECT password FROM users WHERE email = ? AND enabled = true
jdbcRealm.userRolesQuery = SELECT role FROM shiro_user_roles WHERE user_id = (SELECT id FROM users WHERE email = ?)

# Configure JDBC realm password hashing.
credentialsMatcher = org.apache.shiro.authc.credential.HashedCredentialsMatcher
credentialsMatcher.hashAlgorithmName = SHA-256
jdbcRealm.credentialsMatcher = $credentialsMatcher

[urls]
/login.xhtml = user
/pid/** = user
/control/** = user

