
package org.ilu.cmd.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b05
 * Generated source version: 2.2
 */
@WebService(name = "CommandService", targetNamespace = "http://ws.cmd.ilu.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CommandService {


  /**
   * @param arg0
   * @return returns org.ilu.cmd.client.CommandFeedback
   * @throws CommandFeedbackException_Exception
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "submit", targetNamespace = "http://ws.cmd.ilu.org/", className = "org.ilu.cmd.client.Submit")
  @ResponseWrapper(localName = "submitResponse", targetNamespace = "http://ws.cmd.ilu.org/", className = "org.ilu.cmd.client.SubmitResponse")
  @Action(input = "http://ws.cmd.ilu.org/CommandService/submitRequest", output = "http://ws.cmd.ilu.org/CommandService/submitResponse", fault = {
      @FaultAction(className = CommandFeedbackException_Exception.class, value = "http://ws.cmd.ilu.org/CommandService/submit/Fault/CommandFeedbackException")
  })
  public CommandFeedback submit(
      @WebParam(name = "arg0", targetNamespace = "")
          Command arg0)
      throws CommandFeedbackException_Exception
  ;

}
