
package org.ilu.cmd.client;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b05
 * Generated source version: 2.2
 */
@WebServiceClient(name = "CommandServiceImplService", targetNamespace = "http://ws.cmd.ilu.org/", wsdlLocation = "http://localhost:9999/OutputService?WSDL")
public class CommandServiceImplService
    extends Service {

    private final static URL COMMANDSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException COMMANDSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName COMMANDSERVICEIMPLSERVICE_QNAME = new QName("http://ws.cmd.ilu.org/", "CommandServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/OutputService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COMMANDSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        COMMANDSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public CommandServiceImplService() {
        super(__getWsdlLocation(), COMMANDSERVICEIMPLSERVICE_QNAME);
    }

    public CommandServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COMMANDSERVICEIMPLSERVICE_QNAME, features);
    }

    public CommandServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, COMMANDSERVICEIMPLSERVICE_QNAME);
    }

    public CommandServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COMMANDSERVICEIMPLSERVICE_QNAME, features);
    }

    public CommandServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CommandServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns CommandService
     */
    @WebEndpoint(name = "CommandServiceImplPort")
    public CommandService getCommandServiceImplPort() {
        return super.getPort(new QName("http://ws.cmd.ilu.org/", "CommandServiceImplPort"), CommandService.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns CommandService
     */
    @WebEndpoint(name = "CommandServiceImplPort")
    public CommandService getCommandServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.cmd.ilu.org/", "CommandServiceImplPort"), CommandService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COMMANDSERVICEIMPLSERVICE_EXCEPTION != null) {
            throw COMMANDSERVICEIMPLSERVICE_EXCEPTION;
        }
        return COMMANDSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
