
package org.ilu.cmd.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b05
 * Generated source version: 2.2
 */
@WebFault(name = "CommandFeedbackException", targetNamespace = "http://ws.cmd.ilu.org/")
public class CommandFeedbackException_Exception
    extends Exception {

  /**
   * Java type that goes as soapenv:Fault detail element.
   */
  private CommandFeedbackException faultInfo;

  /**
   * @param message
   * @param faultInfo
   */
  public CommandFeedbackException_Exception(String message, CommandFeedbackException faultInfo) {
    super(message);
    this.faultInfo = faultInfo;
  }

  /**
   * @param message
   * @param faultInfo
   * @param cause
   */
  public CommandFeedbackException_Exception(String message, CommandFeedbackException faultInfo, Throwable cause) {
    super(message, cause);
    this.faultInfo = faultInfo;
  }

  /**
   * @return returns fault bean: org.ilu.cmd.client.CommandFeedbackException
   */
  public CommandFeedbackException getFaultInfo() {
    return faultInfo;
  }

}
